import MainLayout from '@/layouts/MainLayout';
import '@/styles/globals.css';

export const metadata = {
  title: 'BL',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <MainLayout>
          { children }
        </MainLayout>
      </body>
    </html>
  )
}
